;;
;; middleware-favicon
;;
;; Serve a basic favicon to browsers that request it.
;;

(module
 middleware-favicon
 (middleware-favicon)

 (import scheme)
 (import chicken-express)

 (require-extension base64)

 (define* (middleware-favicon)
   "Middleware that sends a favicon."
   (let ((favicon (base64-decode "AAABAAEAEBAAAAAAAABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+EAJj/hAD//4QA//+EANT/hACYAAAAAAAAAAAAAAAA/4QAmP+EANT/hAD//4QA//+EAP//hAD//4QAmP+EAJj/hAD//4QA//+EAP//hAD//4QA//+EANQAAAAAAAAAAP+EANT/hAD//4QA//+EAP//hAD//4QA//+EAJj/hADU/4QA//+EAJgAAAAAAAAAAP+EAP//hAD/AAAAAAAAAAD/hAD//4QA/wAAAAAAAAAAAAAAAAAAAAAAAAAA/4QA//+EAP8AAAAAAAAAAAAAAAD/hAD//4QA/wAAAAAAAAAA/4QA//+EAP8AAAAAAAAAAAAAAAAAAAAAAAAAAP+EAP//hAD/AAAAAAAAAAAAAAAA/4QA1P+EANQAAAAAAAAAAP+EAP//hAD/AAAAAAAAAAAAAAAAAAAAAAAAAAD/hAD//4QA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/hAD//4QA/wAAAAAAAAAAAAAAAAAAAAAAAAAA/4QA//+EAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4QA//+EAP//hAD//4QA//+EAP//hAD/AAAAAP+EAP//hAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+EAP//hAD//4QA//+EAP//hAD//4QA/wAAAAD/hAD//4QA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/hAD//4QA/wAAAAAAAAAAAAAAAAAAAAAAAAAA/4QA//+EAP8AAAAAAAAAAAAAAAD/hADU/4QA1AAAAAAAAAAA/4QA//+EAP8AAAAAAAAAAAAAAAAAAAAAAAAAAP+EAP//hAD/AAAAAAAAAAAAAAAA/4QA//+EAP8AAAAAAAAAAP+EAP//hAD/AAAAAAAAAAAAAAAAAAAAAAAAAAD/hADU/4QA//+EAJgAAAAAAAAAAP+EAP//hAD/AAAAAAAAAAD/hAD//4QA/wAAAAAAAAAAAAAAAAAAAAAAAAAA/4QAmP+EAP//hAD//4QA//+EAP//hAD//4QA1AAAAAAAAAAA/4QA1P+EAP//hAD//4QA//+EAP//hAD//4QAmAAAAAD/hACY/4QA//+EAP//hADU/4QAmAAAAAAAAAAAAAAAAP+EAJj/hADU/4QA//+EAP//hAD//4QA//+EAJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAIOAAAABgAAAGZ8AADmfAAA5nwAAP58AAD+BAAA/gQAAP58AADmfAAA5nwAAGZ8AAAGAAACDgAAA//8AAA==")))
     (lambda (self req res next)
       (if (string=? {?req.path} "/favicon.ico")
          ; TODO set proper headers for content-type
          {@res.send favicon})
         (next)))))
